apiVersion: v1
kind: Template
labels:
  template: stage-pipeline
message: A Jenkins server will be automatically instantiated in this project to manage
  the Pipeline BuildConfig created by this template.  You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: ${NEXT_STAGE}-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: stage-pipeline
    labels:
      application: stage-pipeline
  spec:
    triggers: []
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: 'https://github.com/microservices-cicd/pipeline.git'
        ref: master
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: stage-pipeline/Jenkinsfile
    output: {}
    resources: {}
    postCommit: {}
    nodeSelector: {}
parameters:
- name: CURRENT_NAMESPACE
  required: true
  description: 'The current namespace'
- name: NAMESPACE
  required: true
  description: 'The stage namespace'
- name: VERSION
  required: true
  description: 'The version for the image streams'
- name: CURRENT_STAGE
  required: true
- name: NEXT_STAGE
  required: true
