// use the local ocp cluster
openshift.withCluster() {

    def CURRENT_NAMESPACE = "m-cicd-dev"
    def NAMESPACE = "m-cicd-qa"
    def VERSION = "v1.0"
    def CURRENT_STAGE = "dev"
    def NEXT_STAGE = "qa"
    
    // use the current namespace
    openshift.withProject(CURRENT_NAMESPACE) {

        echo "CURRENT_NAMESPACE ${CURRENT_NAMESPACE}"
        echo "NAMESPACE ${NAMESPACE}"
        echo "VERSION ${VERSION}"
        echo "CURRENT_STAGE ${CURRENT_STAGE}"
        echo "NEXT_STAGE ${NEXT_STAGE}"
        
        try {
            // run the pipeline on a node
            node {
                // the build stage
                stage("Test") {
                 echo "test"
                }
            }
        
        } catch(e) {
            error "${e}"
        }
    }
}

